services:
  db:
    image: postgres:17.4-alpine
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
  redis:
    image: redis:7.4.2-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
  django:
    build: .
    volumes:
      - .:/app
    container_name: django-docker
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DEBUG: ${DEBUG}
      DJANGO_LOGLEVEL: ${DJANGO_LOGLEVEL}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
      DATABASE_ENGINE: ${DATABASE_ENGINE}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      REDIS_URL: "redis://redis:6379/0"
    env_file:
      - .env
  goldprice-api:
    build:
      context: goldapi/gold-api-kt-backend
      dockerfile: Dockerfile
    container_name: goldprice-api
    profiles:
      - donotstart
    restart: unless-stopped
    volumes:
      - ./goldapi/goldapi-kt-backend/price_data:/app/price_data


volumes:
  pgdata:
  redisdata:
