# Generated by Django 5.1.6 on 2025-03-29 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produt', '0004_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('p', 'Pending'), ('c', 'Completed')], default='p', max_length=1),
        ),
    ]
