# Generated by Django 5.1.6 on 2025-04-13 18:34

import produt.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produt', '0005_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Baner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to=produt.models.banner_image_path)),
                ('silde', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='special_sale',
            field=models.BooleanField(default=False),
        ),
    ]
