# Generated by Django 5.1.6 on 2025-04-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produt', '0006_baner_product_discount_product_special_sale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='Labor_wage',
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
