# Generated by Django 5.1.6 on 2025-04-14 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produt', '0007_rename_price_product_labor_wage_product_weight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Labor_wage',
            new_name='labor_wage',
        ),
    ]
